runtime: python39  
entrypoint: gunicorn -b :$PORT gestion_bibliotheque.wsgi:application

# Environment variables
env_variables:
  DJANGO_SETTINGS_MODULE: gestion_bibliotheque.settings
  SECRET_KEY: 'django-insecure-%zm@jg3bi+mkj*hgzb^*5bnqk(h&$x!-k1*^1!46)$0j04y2ex'

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

# Optional scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5

