# Generated by Django 3.1.12 on 2024-11-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('statut_emprunt', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=50)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.abonne')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.document')),
            ],
        ),
    ]
